"""Seeded experimental ecology. Only completed-body ACK dt advances this world.

The focal fly pose is an INPUT from Godot, never generated by this module.
NPC movement and physiology are intentionally simple world models, not neural claims.
"""
import copy
import math
import random


def distance(a,b):
    return math.sqrt(sum((x-y)**2 for x,y in zip(a,b)))


def bearing(a,b,yaw):
    dx,dz=b[0]-a[0],b[2]-a[2]
    # Godot forward=(-sin(yaw),0,-cos(yaw)); positive bearing = right.
    return math.atan2(math.sin(math.atan2(dx,-dz)+yaw),math.cos(math.atan2(dx,-dz)+yaw))


class World:
    def __init__(self,cfg):
        self.cfg=copy.deepcopy(cfg); self.rng=random.Random(cfg['world_seed'])
        self.time=0.; self.fly=[0.,.22,0.]; self.yaw=0.
        self.hp=cfg['initial_hp']; self.hunger=cfg['initial_hunger']; self.gut=cfg['initial_gut']
        self.entities={}; self.serial=0; self.events=[]; self.prev_geometry={}; self.previous_temp=cfg['ambient_c']
        self.in_shade=False; self.contacts=set(); self.defecate_at=None; self.heat_start=None
        # Pre-sample the entire schedule: no frame-rate-dependent Bernoulli trials.
        self.schedule=[]
        for kind in ['food','predator','female','heat']:
            at=self.rng.uniform(*cfg[kind]['interval_s'])
            while at<cfg['horizon_s']:
                self.schedule.append(self.plan(kind,at)); at+=self.rng.uniform(*cfg[kind]['interval_s'])
        self.schedule.extend(copy.deepcopy(cfg['initial_events']))
        self.schedule.sort(key=lambda e:(e['at_s'],e['kind']))
        self.initial_schedule=copy.deepcopy(self.schedule); self.sensor=self.sense(0.)

    def plan(self,kind,at):
        angle=self.rng.uniform(-math.pi,math.pi)
        pos=[3.5*math.sin(angle),.3 if kind=='predator' else .22,3.5*math.cos(angle)] if kind=='predator' else [self.rng.uniform(-3.4,3.4),.22,self.rng.uniform(-3.4,3.4)]
        row=dict(kind=kind,at_s=at,position=pos)
        if kind=='female':
            t=0.; row['wander']=[]
            while t<self.cfg['female']['lifetime_s']:
                row['wander'].append([t,self.rng.uniform(-math.pi,math.pi)])
                t+=self.rng.uniform(*self.cfg['female']['wander_interval_s'])
        return row

    def event(self,name,**data):
        self.events.append(dict(event=name,world_time_s=self.time,**data))

    def spawn(self,plan):
        kind=plan['kind']
        if kind=='heat':
            self.heat_start=self.time; self.event('HEAT_START'); return
        self.serial+=1; ident=f'{kind}-{self.serial}'
        entity=dict(id=ident,kind=kind,position=list(plan['position']),radius=self.cfg[kind]['radius'],born_s=self.time,
                    expires_s=self.time+self.cfg[kind]['lifetime_s'],next_hit_s=self.time,wander=plan.get('wander',[[0.,0.]]))
        self.entities[ident]=entity; self.event(kind.upper()+'_SPAWN',entity=copy.deepcopy(entity))

    def manual_event(self,kind):
        if kind=='defecation':
            self.gut=max(self.gut,self.cfg['defecation']['threshold']+1.)
            self.event('TEST_GUT_LOAD',classification='PHYSIOLOGY_PLACEHOLDER'); return
        self.spawn(self.plan(kind,self.time))

    def ambient(self):
        c=self.cfg['ambient_c']; h=self.cfg['heat']
        if self.heat_start is None: return c
        age=self.time-self.heat_start
        if age<h['ramp_s']: return c+(h['peak_c']-c)*age/h['ramp_s']
        age-=h['ramp_s']
        if age<h['hold_s']: return h['peak_c']
        age-=h['hold_s']
        if age<h['recover_s']: return h['peak_c']+(c-h['peak_c'])*age/h['recover_s']
        self.heat_start=None; self.event('HEAT_END'); return c

    def local_temperature(self,pose):
        shade=self.cfg['shade']; inside=all(abs(pose[k]-shade['center'][k])<=shade['half_size'][k] for k in [0,2])
        return self.ambient()-(shade['cooling_c'] if inside else 0.),inside

    def advance(self,dt,pose,yaw,feeding_hz=0.):
        if not math.isfinite(dt) or dt<0 or dt>.0500001: raise ValueError('Only completed neural quantum dt accepted')
        if len(pose)!=3 or not all(math.isfinite(x) for x in pose+[yaw,feeding_hz]): raise ValueError('Nonfinite body ACK')
        self.fly=list(pose); self.yaw=yaw; self.time=round(self.time+dt,10)
        while self.schedule and self.schedule[0]['at_s']<=self.time+1e-9: self.spawn(self.schedule.pop(0))
        for ident,e in list(self.entities.items()):
            if self.time>=e['expires_s']:
                self.event(e['kind'].upper()+'_DESPAWN',entity_id=ident); del self.entities[ident]; continue
            if e['kind']=='predator':
                # Scripted NPC only: pursuit never determines focal fly motor outputs.
                delta=[self.fly[k]-e['position'][k] for k in range(3)]; delta[1]=0.
                d=math.sqrt(sum(x*x for x in delta)); travel=min(d,self.cfg['predator']['speed']*dt)
                if d>0: e['position']=[e['position'][k]+delta[k]/d*travel for k in range(3)]
                if distance(e['position'],self.fly)<=e['radius']+.19 and self.time+1e-9>=e['next_hit_s'] and self.hp>0:
                    self.event('PREDATOR_HIT',entity_id=ident,distance=distance(e['position'],self.fly))
                    before=self.hp; self.hp=max(0.,self.hp-self.cfg['predator']['damage']); e['next_hit_s']=self.time+self.cfg['predator']['hit_cooldown_s']
                    self.event('DAMAGE',amount=before-self.hp,hp=self.hp,pain_level='DISABLED_UNRESOLVED')
                    if self.hp==0: self.event('DEATH')
            elif e['kind']=='female':
                age=self.time-e['born_s']; angle=[x[1] for x in e['wander'] if x[0]<=age][-1]
                e['position'][0]=max(-3.4,min(3.4,e['position'][0]+math.sin(angle)*self.cfg['female']['speed']*dt))
                e['position'][2]=max(-3.4,min(3.4,e['position'][2]+math.cos(angle)*self.cfg['female']['speed']*dt))
        self.hunger=min(100.,self.hunger+self.cfg['hunger_per_s']*dt)
        self.gut=max(0.,self.gut-self.cfg['gut_processing_per_s']*dt)
        contacts=set()
        for ident,e in self.entities.items():
            if e['kind'] not in ['food','female']: continue
            contact=distance(self.fly,e['position'])<=e['radius']+.19
            if contact:
                contacts.add(ident)
                if ident not in self.contacts: self.event(e['kind'].upper()+'_CONTACT',entity_id=ident)
            # Off until functional upstream->Fdg gate certification; never auto-eat on contact.
            if e['kind']=='food' and contact and self.cfg['food']['ingestion_enabled'] and feeding_hz>=self.cfg['food']['feeding_gate_hz'] and self.hp>0:
                amount=self.cfg['food']['ingestion_per_s']*dt
                self.hunger=max(0.,self.hunger-amount); self.gut=min(100.,self.gut+amount)
                if amount: self.event('FOOD_INGEST',amount=amount,feeding_hz=feeding_hz,gate_hz=self.cfg['food']['feeding_gate_hz'],entity_id=ident)
        self.contacts=contacts
        if self.gut>self.cfg['defecation']['threshold'] and self.defecate_at is None:
            self.defecate_at=self.time+self.rng.uniform(*self.cfg['defecation']['latency_s'])
            self.event('DEFECATION_PENDING',at_s=self.defecate_at,classification='PHYSIOLOGY_PLACEHOLDER')
        if self.defecate_at is not None and self.time+1e-9>=self.defecate_at:
            self.gut=max(0.,self.gut-self.cfg['defecation']['gut_drop']); self.defecate_at=None;self.serial+=1
            ident=f'feces-{self.serial}'
            self.entities[ident]=dict(id=ident,kind='feces',position=[self.fly[0],.07,self.fly[2]],radius=.09,born_s=self.time,expires_s=self.time+self.cfg['defecation']['lifetime_s'])
            self.event('DEFECATE',classification='PHYSIOLOGY_PLACEHOLDER',gut=self.gut,entity_id=ident)
        self.sensor=self.sense(dt)

    def sense(self,dt):
        temp,shaded=self.local_temperature(self.fly)
        if shaded!=self.in_shade: self.event('SHADE_ENTER' if shaded else 'SHADE_EXIT')
        self.in_shade=shaded
        figures=[]; food=pheromone=taste=female_contact=0.; distances={k:None for k in ['food','predator','female']}
        next_geometry={}
        for ident,e in self.entities.items():
            d=distance(self.fly,e['position']); kind=e['kind']
            if kind in distances: distances[kind]=min(distances[kind],d) if distances[kind] is not None else d
            if kind=='food': food+=math.exp(-d/self.cfg['food']['odor_scale']);taste=max(taste,float(d<=e['radius']+.19))
            elif kind=='female': pheromone+=math.exp(-d/self.cfg['female']['pheromone_scale']);female_contact=max(female_contact,float(d<=e['radius']+.19))
            if kind in ['predator','female']:
                size=math.degrees(2*math.atan2(e['radius'],max(d,1e-6))); angle=bearing(self.fly,e['position'],self.yaw)
                old=self.prev_geometry.get(ident); expansion=max(0.,(size-old[0])/dt) if old and dt else 0.
                angular=abs(math.degrees(math.atan2(math.sin(angle-old[1]),math.cos(angle-old[1]))))/dt if old and dt else 0.
                next_geometry[ident]=(size,angle)
                figures.append(dict(angular_size_deg=size,positive_expansion_deg_s=expansion,bearing_radians=angle,
                    angular_motion_deg_s=angular+expansion/2.,contrast=1.0 if kind=='predator' else .35))
        rate=(temp-self.previous_temp)/dt if dt else 0.;self.previous_temp=temp;self.prev_geometry=next_geometry
        # No entity identity, target position, desired direction, hunger or HP in sensory primitives.
        self.distances=distances
        return dict(figures=figures,food_odor=min(food,1.),contact_sugar=taste,fly_odor=min(pheromone,1.),
                    contact_cuticle=female_contact,temperature_c=temp,temperature_change_c_s=rate)

    def snapshot(self):
        return dict(world_time_s=self.time,fly_position=list(self.fly),fly_yaw=self.yaw,hp=self.hp,hunger=self.hunger,gut=self.gut,
                    ambient_c=self.ambient(),local_temperature_c=self.sensor['temperature_c'],in_shade=self.in_shade,
                    entities=copy.deepcopy(list(self.entities.values())),distances=copy.deepcopy(self.distances),raw_sensors=copy.deepcopy(self.sensor),
                    ingestion_level='EXPERIMENTAL_UNCERTIFIED_TEST_ONLY' if self.cfg['food']['ingestion_enabled'] else 'DISABLED_UNRESOLVED',
                    defecation_level='PHYSIOLOGY_PLACEHOLDER',pain_level='DISABLED_UNRESOLVED')


def load_config(path,mode=None):
    import json
    cfg=json.loads(open(path,encoding='utf-8').read())
    if cfg['food']['ingestion_enabled'] or cfg['sensory']['pain_enabled'] or cfg['sensory']['female_contact_enabled']:
        raise ValueError('Unresolved feeding/pain/contact mappings cannot be enabled by a config flag')
    if mode=='certification':
        cfg.update(mode=mode,certification=True,horizon_s=10.,duration_s=3.0,initial_gut=75.)
        for name in ['food','predator','female','heat']: cfg[name]['interval_s']=[20.,30.]
        cfg['predator'].update(speed=3.0,lifetime_s=1.8)
        cfg['food']['lifetime_s']=2.5
        cfg['female'].update(lifetime_s=1.5,speed=.15)
        cfg['heat'].update(ramp_s=.4,hold_s=.6,recover_s=.4)
        cfg['initial_events']=[dict(kind='food',at_s=0.,position=[0.,.22,0.]),dict(kind='predator',at_s=.15,position=[.8,.3,-2.5]),
                               dict(kind='female',at_s=.2,position=[.3,.22,0.],wander=[[0.,1.0],[.5,-1.0]]),dict(kind='heat',at_s=.3)]
    return cfg
